### ISSUE TITLE
Without extra bag slots, Item quality and level are offset by 4

### ISSUE THREAD

**Issue by raymondwilliamskc** [d4kir92/ImproveAny#3]
In the main bag, on both combined and separate bags, if the "extra" slots unlocked by SMS protect are not available, the item quality and level border are offset by 4 (the number of extra slots)

![image](https://user-images.githubusercontent.com/15200711/206574796-f94cee97-2d77-4ce2-8637-dd1be55b222e.png)

![image](https://user-images.githubusercontent.com/15200711/206574898-d7357c79-08f8-466c-a064-7839782504c9.png)

**Comment by d4kir92** [comment]
Fixed
